### PR TITLE
Cookie dance [TB-221]

### PR DESCRIPTION
**Pull request by jankoulaga**
The flow goes like this.... Request is received, and if it does not exits, the 3rd party cookie is added and request is redirected back to /i with a n3pc parameter. Then a check is done if it was a redirect with n3pc and if the cookie was properly set. If it wasn't, obviously the browser does not accept 3rd party cookies and the fallbackNetworkId is set.

### CODE REVIEW

**Comment by christoph-buente** [comment]
Looks good, despite the spaghetti handler code.

**Comment by jalkjaer** [comment]
The code is not super simple to follow, but it seems that even though `shouldRedirect` is true the event is still pushed to kinesis, instead of relying on the event coming back in the redirect millis later

**Comment by christoph-buente** [comment]
@jankoulaga Can you provide a test case to make sure the event is only sent once to kinesis?

**Comment by jankoulaga** [comment]
@jalkjaer yeah, you're right. I did not add the check for kinesis before. it is added now.
About the readability, there is not much i can do without a lot of interventions.

**Comment by jankoulaga** [comment]
@christoph-buente will do!

**Comment by jankoulaga** [comment]
@jalkjaer, @christoph-buente  i added the tests to check if storing to kinesis is called in case of non existing 3rd party cookie.

**Comment by christoph-buente** [comment]
@jankoulaga Thx a bunch!

**Comment by jalkjaer** [comment]
@jankoulaga I agree - and too much rewriting will probably make it harder to get an upstream PR accepted :)

**Comment by jankoulaga** [comment]
@jalkjaer that's exactly what @christoph-buente said, and i had a hard time restraining myself from refactoring half of it. I hope that adding an extra lib for tests won't put them off, but in the end, i don't understand why they aren't using Mockito in the first place.

**Comment by christoph-buente** [comment]
👍  now, thx @jankoulaga 
@jalkjaer thumbs up too?

**Comment by jankoulaga** [comment]
@christoph-buente added a config parameter with which someone can enable our n3pc logic. By default it's set to false, and if it does not exist in the config fallbacks to disabled n3pc redirects.

**Pull request closed without merging**
